### ISSUE TITLE
Add totalTax to TaxedPrice interface

### ISSUE THREAD

**Issue by rezaerami** [commercetools/commercetools-sdk-typescript#246]
in the TaxedPrice interface, there are only totalNet, totalGross, and taxPortions properties, but in the response of an order you can see totalTax property also

**Comment by ajimae** [comment]
Hi @rezaerami 

Thanks for reporting this issue, we will get this fixed as soon as we can.

Thanks.

**Comment by ashishhk** [comment]
Next action: Investigation is required to check in the code generator why its missing the Total Tax in TaxedPrice interface, also make sure its working for the other SDKs.

**Comment by barbara79** [comment]
Hi @rezaerami ,
 [the TaxedPrice interface](https://github.com/commercetools/commercetools-sdk-typescript/blob/main/packages/importapi-sdk/src/generated/models/orders.ts), now contains the totalTax property.

Could you please confirm that this issue is solved in a newer release of the Typescript SDK?

Thanks and Regards,
Barbara Palumbo

**Comment by barbara79** [comment]
I will close this issue but if you have any questions please feel free to ask us. :)
