### ISSUE TITLE
Add missing fields to InvalidInputError type

### ISSUE THREAD

**Issue by melih154** [commercetools/commercetools-sdk-typescript#247]
Thanks for this great library, helps a lot.

Can you please add `itemIdentification`, `resourceId `and `resourceIdentifier` fields to `InvalidInputError` type? Errors only contains code and message, where as Commercetools API includes `itemIdentification`, `resourceId `and `resourceIdentifier` fields on errors section.

Trying to implement an API that returns a validation error message type (not message) on API response. You can test it on [add line item to my cart](https://docs.commercetools.com/api/projects/me-carts#add-lineitem) by setting line item sku as an invalid one.

CT API Response

```
{
    "statusCode": 400,
    "message": "LineItem error: No published product with an sku 'invalidSKU' exists.",
    "errors": [
        {
            "code": "InvalidInput",
            "message": "LineItem error: No published product with an sku 'invalidSKU' exists.",
            "itemIdentification": {
                "sku": "invalidSKU",
                "type": "LineItemSkuIdentification"
            },
            "resourceId": "xxxxx",
            "resourceIdentifier": "cart"
        }
    ]
}
```

CT TS SDK Response
`[{"code":"InvalidInput","message":"No published product with an sku 'invalidSKU' exists."}]
`

**Comment by ajimae** [comment]
Hi @melih154 

Thanks for reporting this, we will look at it and see how we can go about implementing it.

Regards

**Comment by jenschude** [comment]
The issue comes from the fact that the InvalidInput error is a quite generic one. And according to the [docs](https://docs.commercetools.com/api/errors#400-bad-request-1) no additional fields are specified. And as we don't have a formal specification of the fields we can't rely on them being in the response and implement them in the SDKs.

You should be able to access any key of the InvalidInputError but you will not get back a type safe object:

https://github.com/commercetools/commercetools-sdk-typescript/blob/000f3f728500f36a71ccc24e91ee7160aad8bfd1/packages/platform-sdk/src/generated/models/error.ts#L533-L540
