### ISSUE TITLE
[Question]: How to fetch an anonymous My Cart after a browser refresh such that the SDK has already lost the refresh token?

### ISSUE THREAD

**Issue by iamrenejr** [commercetools/commercetools-sdk-typescript#467]
Hello! We're using the CT TS SDK for our current project, and I have a CT JS Associate certification myself. My team and I were talking about this scenario and if this is a case supported by the CT TS SDK, which we're trying to use as opposed to calling all the API endpoints ourselves.

Here is the scenario: the frontend is directly interacting with CT (so the client's permissions are severely restricted), and a user is unauthenticated and has an anonymous My Cart. The cart is created this way:
```
  anonApiRoot
    .me()
    .carts()
    .post({
      body: {
        inventoryMode: 'ReserveOnOrder',
        currency,
        country,
      },
    })
    .execute();
```

The client itself was created with `.withAnonymousSessionFlow()`, like this:
```
  return createClientBuilder()
    .withAnonymousSessionFlow(authOptions)
    .withHttpMiddleware(httpOptions)
    .withLoggerMiddleware()
    .build();
```

The user adds some items to cart - great, it works.

But now when they refresh the page, the cart disappears, because the SDK loses the refresh token and creates a new anonymous cart.

Is there a way to extract and save the refresh token used by the SDK, or to make the SDK remember it so that refreshing the window does not lose the token?

Or, is this going about it the wrong way? Should we already be in possession of a refresh token ourselves by calling the CT APIs without the SDK, and then feed that refresh token to the SDK via `.withRefreshTokenFlow`?

Thank you!

**Comment by jenschude** [comment]
Not directly. A possibility is to initialise the anonymous flow with a token cache using the local storage of the browser.

**Comment by ajimae** [comment]
Hi @iamrenejr 

A complete example on how to create, add and deleting items in an **anonymous cart** has already been implemented and the cart state also persists between browser refresh.

Please refer to [this example](https://github.com/commercetools/commercetools-sdk-typescript/tree/master/examples/me) to learn more on how this was achieved.

Thanks

**Comment by ajimae** [comment]
You can easily follow this steps to solve this issue:

1. When using the anonymous session flow, you first make a request (optionally supplying an anonymousId option) to retrieve an `anonymous token` as a response (this is handled by the SDK). 
2. You need to [access the returned token](https://github.com/commercetools/commercetools-sdk-typescript/issues/314) and store it in your preferred browser storage.
3.  Then, you can access and use the stored token in your request headers when making subsequent calls to our services.

Alternatively, just as @jenschude pointed, the SDK stores the token internally too and reuses it to make requests. See [this issue](https://github.com/commercetools/commercetools-sdk-typescript/issues/353) to learn how this can be achieved.

Thanks

**Comment by iamrenejr** [comment]
Thanks @jenschude and @ajimae, and sorry for responding just now. We went with the token cache solution as it was much cleaner and didn't need workarounds. We moved the login calls to CT server side, which meant we had to give the access-restricted tokens to the client somehow, since we use the SDK on both client and server. Extracting the info from the token cache made doing that much easier. Thanks!

**Comment by ajimae** [comment]
Hi @fhaertig,

- I believe with a simple logic you can easily create a dynamic authentication for users based on the user's initial credentials.
- For creating a single client before hand to use for all authentication flows currently is not possible as different flows required different authentication options, however, you can create a single client instance by passing in the specific options for the respective auth flow.
- This is not a design error, this is done in order to give our users the option to use the best authentication flow that uniquely suit their needs.

For an anonymous user (that is a user without a username and a password) you can assign them an optional unique `anonymousId` using the anonymous token flow, an anonymous token will be issued and this token can be accessed and saved/cached, and all subsequent requests needs to be made with this token as the `Authorization` header. I similar implementation can be found [here](https://github.com/commercetools/commercetools-sdk-typescript/blob/master/examples/me/server/src/client/Client.ts) and also you can draw some insight from this [link](https://github.com/commercetools/commercetools-sdk-typescript/issues/353) as well.

**Comment by fhaertig** [comment]
Thanks for the fast response! 

The anonymous user is not the problem, but keeping track of logged in users is. I don't want to be stateful, so my approach is:
1. get credentials from user in Frontend
2. do the login with commercetools in backend, create token
3. encrypt token, handover to frontend
4. keep track of token in Cookies as long as valid and logged in

Therefore, authenticated users are able to execute requests as long as the token is valid and correctly appended. This worked fine in v1, but now I am required to create a new API client everytime somebody needs to do an authenticated request due to the way the AuthOptions are constructed. 
The other option would be to cache every API client connected to any authenticated user once created. This feels very cumbersome. 

The referenced code parts show exactly the problem if I am not mistaken. At least I can't find a caching mechanism for CustomerRepository or Client there. For now, I still don't have a solution.

**Comment by jenschude** [comment]
The apparent issue here is, that the Me endpoints are not meant to be used server side. If you use them client side it's way simpler to keep track of session data as it stays in the browser. Server side you have to have some session based storage for the different client tokens

**Comment by jenschude** [comment]
Also if passing through you still be able to either create a short lived client with the existing token.

You can then create an ApiRoot using this client. Or you just create use the `clientRequest` method of the ApiRoots call chains and use `client.execute(ClientRequestInstance)` cause the `execute` method does nothing more than wrapping this call in the request itself.

**Comment by fhaertig** [comment]
Although this is a nice suggestion and some good insight, it still means that the sdk-v2 client is stateful. For me this is a major flaw and restrains me from using it in a server-side nodejs application. I don't uderstand why this was changed in particular.
Of course, I'm always free to wrap the calls in a custom way. For now I will stay in v1 sdk.

Please consider noting this in the README or in the docs, because its a bit unclear on how to actually use the middlewares.
Again, thanks for the help!

**Comment by jenschude** [comment]
Btw what i don't see from your description. How did you injected the token into the client in v1?

**Comment by ajimae** [comment]
@fhaertig you can use the v1 syntax in the v2 also. See this [link](https://github.com/commercetools/commercetools-sdk-typescript/tree/master/packages/sdk-client#node-environment) on how to do this.

Also, I noticed you haven't shown us how you were able to achieve this functionality in v1 and the packages you are using in the v1 SDK, a code snippet will be sufficient, this will help us see if we can replicate it in the v2 SDK.


Thanks

**Comment by fhaertig** [comment]
@ajimae I appreciate the effort, it's quite undocumented but actually might help me in setting this up. There is just a minor issue in the Middleware type in sdk-v2 (Error is "'host' does not exist in type 'Middleware'").
By the way: it's also the way we used v1 sdk - chaining the middlewares including a custom one where the token was appended conditionally. But this is not the topic here.

**Comment by ajimae** [comment]
Please feel free to reopen is issue still persists.
