### ISSUE TITLE
Support the batching with process in commercetools-sdk-typescript project or document it.

### ISSUE THREAD

**Issue by ashishhk** [commercetools/commercetools-sdk-typescript#55]
I figured out the new commercetools-sdk-typescript does not have an easy solution for the batching, which already exists of the exposed @commercetools/sdk-client but this is not easy to see if you don't know already how it could be done with this package, as it is not sth documented.

https://github.com/commercetools/nodejs/blob/master/packages/sdk-client/src/client.js#L81-L85

In the project, returned API root only sees the execute method of the created ctp client. So in batching needs, I needed to write an additional boilerplate code as said not easy to reason, maybe you might consider supporting that utility as part of the new library.

My snippet to expose process method,
````
function processBatches(uri, callback) {
const ctpClient = getCtpClient()
const requestOptions = {
uri,
method: 'GET',
headers:

{ Accept: 'application/json', 'Content-Type': 'application/json', }
,
}
return ctpClient.process(
requestOptions,
(data) => callback(data.body.results),

{ accumulate: false }
)
}
````

**Comment by jenschude** [comment]
A simpler solution is to use the clientRequest method of the ApiRequest class.

```

**Comment by ahmetoz** [comment]
Hi @jenschude 
I'm doing the same in my code. 

The process method is part of the ctpClient, apiRoot could expose the process method in a nicer way (Not sure about the best strategy here). 
Otherwise, you need to keep the state of the ctpClient object, The problem I see it's not easy to see without knowing there is a process method for batching pagination needs. Because we are using apiRoot for the type-safe method structure working with ctpClient again is not easy to reason, if you have not used the process method before. Maybe you could expose the process method part of the apiRoot ?
